version: "3.7"
services:
  app:
    build: chatandvideo
    ports:
      - "3000:3000"
    networks:
      - my-pre-existing-network

networks:
  proxy:
    external:
      name: my-pre-existing-network
