version: "3.9"
services:
  app:
    build: chatandvideo
    ports:
      - "3000:3000"
    networks:
      - proxy
  proxy:
    image: nginx
    networks:
      - proxy
    ports:
      - "80:80"
    volumes:
      - vhost.conf:/etc/nginx/conf.d/vhost.conf

networks:
  proxy:
    driver: custom-driver-1