version: "3.7"
services:
  app:
    build: chatandvideo
    ports:
      - "3000:3000"
    depends_on:
      - proxy
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/videoAndChatApp/vhost.conf:/etc/nginx/conf.d/vhost.conf
