version: "3.7"
services:
  app:
    image: videochat_app_test1:$BUILD_NUMBER
    container_name: videochat_app_1
    build: .
#    ports:
#      - "3000:3000"
    networks:
      - proxy
    environment:
      PRODUCTION: 'true'
      NUMBER: '1'
  testOne:
    image: videochat_app_test2:$BUILD_NUMBER
    container_name: videochat_app_1
    build: .
#    ports:
#      - "3000:3000"
    networks:
      - proxy
    environment:
      PRODUCTION: 'false'
      NUMBER: '1'
  testTwo:
    image: videochat_app_test3:$BUILD_NUMBER
    container_name: videochat_app_1
    build: .
#    ports:
#      - "3000:3000"
    networks:
      - proxy
    environment:
      PRODUCTION: 'false'
      NUMBER: '2'
  testThree:
    image: videochat_app_test3:$BUILD_NUMBER
    container_name: videochat_app_1
    build: .
    #    ports:
    #      - "3000:3000"
    networks:
      - proxy
    environment:
      PRODUCTION: 'false'
      NUMBER: '3'

networks:
  proxy:
    external:
      name: my-pre-existing-network
