version: "3.7"
services:
  app:
    image: videochat_app_1:$BRANCH_NAME.$BUILD_NUMBER
    container_name: videochat_app_1_$BRANCH
    build: .
#    ports:
#      - "3000:3000"
    networks:
      - proxy
    environment:
      PRODUCTION: 'true'
      NUMBER: '1'

networks:
  proxy:
    external:
      name: my-pre-existing-network
