version: "3.7"
services:
  app:
    image: videochat_app_1:$BRANCH.$BUILD_NUMBER
    container_name: videochat_app_1_$BRANCH
    build: .
#    ports:
#      - "3000:3000"
    networks:
      - proxy
    environment:
      PRODUCTION: 'true'
      NUMBER: '1'
    healthcheck:
      test: curl --fail -s http://videochat_app_1_$BRANCH:3000/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

networks:
  proxy:
    external:
      name: my-pre-existing-network
