name: 'CI'
on:
  push:
  pull_request:
jobs:
  test-job:
    runs-on: [self-hosted, linux, x64, gpu]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        name: 'setup'
        with:
          node-version: '14.x'

      - name: 'set up'
        run: |
         cd chatandvideo
         npm i eslint
      - name: 'lint'
        run: |
         cd chatandvideo
         yarn lint
      - name: 'test'
        run: |
         cd chatandvideo
         npm run jest
      - name: 'coverage'
        run: |
         cd chatandvideo
          npm run test -- --coverage --watchAll=false --detectOpenHandles
