name: 'CI'
on:
  push:
  pull_request:
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        name: 'setup'
        with:
          node-version: '14.x'

      - name: 'lint'
        run: |
         yarn add eslint
         cd chatandvideo
         yarn lint
      - name: 'test'
        run: |
         cd chatandvideo
         yarn test
